import { FormControl } from '@angular/forms';
import { CustomerInterface, Photo } from '../constants/Interface';
import { Booking, Contact, Invoice, Payment, Document } from '../constants/Interface';
export class Customer implements CustomerInterface {
  id: number;
  name: string = '';
  province: string = '';
  city: string = '';
  country: number | null = null;
  address: string = '';
  postalCode: string = '';
  document: string = '';
  email: string = '';
  phone: string = '';
  genderId: number | null = null;
  languageId: number | null = null;
  originId: number | null = null;
  nationality: number | null = null;
  tutorId: number | null = null;
  birthDate: Date | null = null;
  typeDoc: number | null = null;
  formControl = new FormControl<Date | null>(null);
  schoolOrCompany: number | null = null;
  bankAcount: string = '';
  contacts: Contact[] = [] as Contact[];
  documents: Document[] = [] as Document[];
  bookings: Booking[] = [] as Booking[];
  invoices: Invoice[] = [] as Invoice[];
  payments: Payment[] = [] as Payment[];
  appLang: string = 'es';
  photo: Photo | null = null;

  constructor(data: CustomerInterface = {} as CustomerInterface ) {
    this.id = data.id;
    this.name = data.name || '';
    this.province = data.province || '';
    this.city = data.city || '';
    this.country = data.country || null;
    this.address = data.address || '';
    this.postalCode = data.postalCode || '';
    this.document = data.document || '';
    this.email = data.email;
    this.phone = data.phone || '';
    this.genderId = data.genderId || null;
    this.languageId = data.languageId || null;
    this.originId = data.originId || null;
    this.nationality = data.nationality || null;
    this.tutorId = data.tutorId || null;
    this.birthDate = data.birthDate || null;
    this.formControl = new FormControl(this.birthDate);
    this.typeDoc = data.typeDoc || null;
    this.schoolOrCompany = data.schoolOrCompany || null;
    this.bankAcount = data.bankAcount || '';
    this.contacts = data.contacts || [];
    this.documents = data.documents || [];
    this.bookings = data.bookings || [];
    this.invoices = data.invoices || [];
    this.payments = data.payments || [];
    this.appLang = data.appLang || 'es';
    this.photo = data.photo || null;
  }
};
